// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventProcessor_ProcessEvent_FullMethodName = "/event.EventProcessor/ProcessEvent"
)

// EventProcessorClient is the client API for EventProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventProcessorClient interface {
	ProcessEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type eventProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewEventProcessorClient(cc grpc.ClientConnInterface) EventProcessorClient {
	return &eventProcessorClient{cc}
}

func (c *eventProcessorClient) ProcessEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventProcessor_ProcessEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventProcessorServer is the server API for EventProcessor service.
// All implementations must embed UnimplementedEventProcessorServer
// for forward compatibility.
type EventProcessorServer interface {
	ProcessEvent(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedEventProcessorServer()
}

// UnimplementedEventProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventProcessorServer struct{}

func (UnimplementedEventProcessorServer) ProcessEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessEvent not implemented")
}
func (UnimplementedEventProcessorServer) mustEmbedUnimplementedEventProcessorServer() {}
func (UnimplementedEventProcessorServer) testEmbeddedByValue()                        {}

// UnsafeEventProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventProcessorServer will
// result in compilation errors.
type UnsafeEventProcessorServer interface {
	mustEmbedUnimplementedEventProcessorServer()
}

func RegisterEventProcessorServer(s grpc.ServiceRegistrar, srv EventProcessorServer) {
	// If the following call pancis, it indicates UnimplementedEventProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventProcessor_ServiceDesc, srv)
}

func _EventProcessor_ProcessEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventProcessorServer).ProcessEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventProcessor_ProcessEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventProcessorServer).ProcessEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventProcessor_ServiceDesc is the grpc.ServiceDesc for EventProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventProcessor",
	HandlerType: (*EventProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessEvent",
			Handler:    _EventProcessor_ProcessEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
